2020-07-10 08:25:10.801400: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2020-07-10 08:25:10.806655: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
WARNING:tensorflow:From /usr/lib/python3/dist-packages/tensorflow_core/python/compat/v2_compat.py:68: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
2020-07-10 08:25:12.251855: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2599990000 Hz
2020-07-10 08:25:12.252078: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x4169d30 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-07-10 08:25:12.252106: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-07-10 08:25:12.254782: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-07-10 08:25:12.362620: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-07-10 08:25:12.362984: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x4310140 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2020-07-10 08:25:12.362999: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): GeForce RTX 2080 with Max-Q Design, Compute Capability 7.5
2020-07-10 08:25:12.363120: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-07-10 08:25:12.363472: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1639] Found device 0 with properties:
name: GeForce RTX 2080 with Max-Q Design major: 7 minor: 5 memoryClockRate(GHz): 1.095
pciBusID: 0000:01:00.0
2020-07-10 08:25:12.363505: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2020-07-10 08:25:12.364589: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2020-07-10 08:25:12.365380: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10.0
2020-07-10 08:25:12.365590: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10.0
2020-07-10 08:25:12.366592: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10.0
2020-07-10 08:25:12.367325: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10.0
2020-07-10 08:25:12.369657: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-07-10 08:25:12.369726: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-07-10 08:25:12.370078: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-07-10 08:25:12.370332: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1767] Adding visible gpu devices: 0
2020-07-10 08:25:12.703130: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1180] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-07-10 08:25:12.703156: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1186]      0
2020-07-10 08:25:12.703161: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1199] 0:   N
2020-07-10 08:25:12.703304: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-07-10 08:25:12.703681: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-07-10 08:25:12.703982: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1325] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 7088 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 with Max-Q Design, pci bus id: 0000:01:00.0, compute capability: 7.5)
TensorFlow:  1.15
Model:       vgg16
Dataset:     imagenet (synthetic)
Mode:        training
SingleSess:  False
Batch size:  48 global
48 per device
Num batches: 100
Num epochs:  0.00
Devices:     ['/gpu:0']
NUMA bind:   False
Data format: NCHW
Optimizer:   sgd
Variables:   replicated
AllReduce:   nccl
==========
Generating training model
WARNING:tensorflow:From /home/ubuntu/lambda-tensorflow-benchmark/benchmarks/scripts/tf_cnn_benchmarks/convnet_builder.py:134: conv2d (from tensorflow.python.layers.convolutional) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.keras.layers.Conv2D` instead.
W0710 08:25:12.715977 140529772136256 deprecation.py:323] From /home/ubuntu/lambda-tensorflow-benchmark/benchmarks/scripts/tf_cnn_benchmarks/convnet_builder.py:134: conv2d (from tensorflow.python.layers.convolutional) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.keras.layers.Conv2D` instead.
WARNING:tensorflow:From /usr/lib/python3/dist-packages/tensorflow_core/python/layers/convolutional.py:424: Layer.apply (from tensorflow.python.keras.engine.base_layer) is deprecated and will be removed in a future version.
Instructions for updating:
Please use `layer.__call__` method instead.
W0710 08:25:12.716767 140529772136256 deprecation.py:323] From /usr/lib/python3/dist-packages/tensorflow_core/python/layers/convolutional.py:424: Layer.apply (from tensorflow.python.keras.engine.base_layer) is deprecated and will be removed in a future version.
Instructions for updating:
Please use `layer.__call__` method instead.
WARNING:tensorflow:From /home/ubuntu/lambda-tensorflow-benchmark/benchmarks/scripts/tf_cnn_benchmarks/convnet_builder.py:266: max_pooling2d (from tensorflow.python.layers.pooling) is deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.MaxPooling2D instead.
W0710 08:25:12.737872 140529772136256 deprecation.py:323] From /home/ubuntu/lambda-tensorflow-benchmark/benchmarks/scripts/tf_cnn_benchmarks/convnet_builder.py:266: max_pooling2d (from tensorflow.python.layers.pooling) is deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.MaxPooling2D instead.
WARNING:tensorflow:From /home/ubuntu/lambda-tensorflow-benchmark/benchmarks/scripts/tf_cnn_benchmarks/convnet_builder.py:408: dropout (from tensorflow.python.layers.core) is deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.dropout instead.
W0710 08:25:12.856150 140529772136256 deprecation.py:323] From /home/ubuntu/lambda-tensorflow-benchmark/benchmarks/scripts/tf_cnn_benchmarks/convnet_builder.py:408: dropout (from tensorflow.python.layers.core) is deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.dropout instead.
WARNING:tensorflow:From /usr/lib/python3/dist-packages/tensorflow_core/python/ops/losses/losses_impl.py:121: where (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
W0710 08:25:12.888998 140529772136256 deprecation.py:323] From /usr/lib/python3/dist-packages/tensorflow_core/python/ops/losses/losses_impl.py:121: where (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
Initializing graph
WARNING:tensorflow:From /home/ubuntu/lambda-tensorflow-benchmark/benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py:2269: Supervisor.__init__ (from tensorflow.python.training.supervisor) is deprecated and will be removed in a future version.
Instructions for updating:
Please switch to tf.train.MonitoredTrainingSession
W0710 08:25:13.082975 140529772136256 deprecation.py:323] From /home/ubuntu/lambda-tensorflow-benchmark/benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py:2269: Supervisor.__init__ (from tensorflow.python.training.supervisor) is deprecated and will be removed in a future version.
Instructions for updating:
Please switch to tf.train.MonitoredTrainingSession
2020-07-10 08:25:13.127716: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-07-10 08:25:13.128048: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1639] Found device 0 with properties:
name: GeForce RTX 2080 with Max-Q Design major: 7 minor: 5 memoryClockRate(GHz): 1.095
pciBusID: 0000:01:00.0
2020-07-10 08:25:13.128070: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2020-07-10 08:25:13.128095: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2020-07-10 08:25:13.128105: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10.0
2020-07-10 08:25:13.128115: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10.0
2020-07-10 08:25:13.128124: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10.0
2020-07-10 08:25:13.128133: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10.0
2020-07-10 08:25:13.128143: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-07-10 08:25:13.128191: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-07-10 08:25:13.128544: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-07-10 08:25:13.128831: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1767] Adding visible gpu devices: 0
2020-07-10 08:25:13.128851: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1180] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-07-10 08:25:13.128858: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1186]      0
2020-07-10 08:25:13.128864: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1199] 0:   N
2020-07-10 08:25:13.128923: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-07-10 08:25:13.129246: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-07-10 08:25:13.129545: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1325] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 7088 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 with Max-Q Design, pci bus id: 0000:01:00.0, compute capability: 7.5)
2020-07-10 08:25:13.187151: W tensorflow/compiler/jit/mark_for_compilation_pass.cc:1586] (One-time warning): Not using XLA:CPU for cluster because envvar TF_XLA_FLAGS=--tf_xla_cpu_global_jit was not set.  If you want XLA:CPU, either set that envvar, or use experimental_jit_scope to enable XLA:CPU.  To confirm that XLA is active, pass --vmodule=xla_compilation_cache=1 (as a proper command-line flag, not via TF_XLA_FLAGS) or set the envvar XLA_FLAGS=--xla_hlo_profile.
INFO:tensorflow:Running local_init_op.
I0710 08:25:13.208485 140529772136256 session_manager.py:500] Running local_init_op.
INFO:tensorflow:Done running local_init_op.
I0710 08:25:13.234554 140529772136256 session_manager.py:502] Done running local_init_op.
Running warm up
2020-07-10 08:25:13.460291: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2020-07-10 08:25:13.608851: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-07-10 08:25:14.909798: I tensorflow/stream_executor/cuda/cuda_driver.cc:831] failed to allocate 2.91G (3120270336 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-07-10 08:25:17.404048: W tensorflow/core/common_runtime/bfc_allocator.cc:305] Garbage collection: deallocate free memory regions (i.e., allocations) so that we can re-allocate a larger region to avoid OOM due to memory fragmentation. If you see this message frequently, you are running near the threshold of the available device memory and re-allocation may incur great performance overhead. You may try smaller batch sizes to observe the performance impact. Set TF_ENABLE_GPU_GARBAGE_COLLECTION=false if you'd like to disable this feature.
2020-07-10 08:25:17.528792: I tensorflow/stream_executor/cuda/cuda_driver.cc:831] failed to allocate 4.91G (5267753984 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-07-10 08:25:17.528891: W tensorflow/core/common_runtime/bfc_allocator.cc:239] Allocator (GPU_0_bfc) ran out of memory trying to allocate 2.81GiB with freed_by_count=0. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
2020-07-10 08:25:17.532108: I tensorflow/stream_executor/cuda/cuda_driver.cc:831] failed to allocate 4.91G (5267753984 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-07-10 08:25:17.532166: W tensorflow/core/common_runtime/bfc_allocator.cc:239] Allocator (GPU_0_bfc) ran out of memory trying to allocate 2.81GiB with freed_by_count=0. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
2020-07-10 08:25:17.629378: I tensorflow/stream_executor/cuda/cuda_driver.cc:831] failed to allocate 4.91G (5267753984 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-07-10 08:25:17.629400: W tensorflow/core/common_runtime/bfc_allocator.cc:239] Allocator (GPU_0_bfc) ran out of memory trying to allocate 1.31GiB with freed_by_count=0. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
2020-07-10 08:25:17.630015: I tensorflow/stream_executor/cuda/cuda_driver.cc:831] failed to allocate 4.91G (5267753984 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-07-10 08:25:17.630026: W tensorflow/core/common_runtime/bfc_allocator.cc:239] Allocator (GPU_0_bfc) ran out of memory trying to allocate 1.31GiB with freed_by_count=0. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
2020-07-10 08:25:17.759145: I tensorflow/stream_executor/cuda/cuda_driver.cc:831] failed to allocate 4.91G (5267753984 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-07-10 08:25:17.759168: W tensorflow/core/common_runtime/bfc_allocator.cc:239] Allocator (GPU_0_bfc) ran out of memory trying to allocate 1.45GiB with freed_by_count=0. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
2020-07-10 08:25:17.759822: I tensorflow/stream_executor/cuda/cuda_driver.cc:831] failed to allocate 4.91G (5267753984 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-07-10 08:25:17.759833: W tensorflow/core/common_runtime/bfc_allocator.cc:239] Allocator (GPU_0_bfc) ran out of memory trying to allocate 1.45GiB with freed_by_count=0. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
2020-07-10 08:25:17.802723: I tensorflow/stream_executor/cuda/cuda_driver.cc:831] failed to allocate 4.91G (5267753984 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-07-10 08:25:17.802748: W tensorflow/core/common_runtime/bfc_allocator.cc:239] Allocator (GPU_0_bfc) ran out of memory trying to allocate 1009.38MiB with freed_by_count=0. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
2020-07-10 08:25:17.803411: I tensorflow/stream_executor/cuda/cuda_driver.cc:831] failed to allocate 4.91G (5267753984 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-07-10 08:25:17.803423: W tensorflow/core/common_runtime/bfc_allocator.cc:239] Allocator (GPU_0_bfc) ran out of memory trying to allocate 1009.38MiB with freed_by_count=0. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
2020-07-10 08:25:17.925244: I tensorflow/stream_executor/cuda/cuda_driver.cc:831] failed to allocate 4.91G (5267753984 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-07-10 08:25:17.925267: W tensorflow/core/common_runtime/bfc_allocator.cc:239] Allocator (GPU_0_bfc) ran out of memory trying to allocate 1.79GiB with freed_by_count=0. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
2020-07-10 08:25:17.925895: I tensorflow/stream_executor/cuda/cuda_driver.cc:831] failed to allocate 4.91G (5267753984 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-07-10 08:25:17.925907: W tensorflow/core/common_runtime/bfc_allocator.cc:239] Allocator (GPU_0_bfc) ran out of memory trying to allocate 1.79GiB with freed_by_count=0. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
2020-07-10 08:25:17.988451: I tensorflow/stream_executor/cuda/cuda_driver.cc:831] failed to allocate 4.91G (5267753984 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-07-10 08:25:17.989066: I tensorflow/stream_executor/cuda/cuda_driver.cc:831] failed to allocate 4.91G (5267753984 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-07-10 08:25:18.058055: I tensorflow/stream_executor/cuda/cuda_driver.cc:831] failed to allocate 4.91G (5267753984 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-07-10 08:25:18.058088: E tensorflow/compiler/xla/service/gpu/cudnn_conv_algorithm_picker.cc:536] Resource exhausted: Out of memory while trying to allocate 633339904 bytes.
2020-07-10 08:25:18.120288: I tensorflow/stream_executor/cuda/cuda_driver.cc:831] failed to allocate 4.91G (5267753984 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-07-10 08:25:18.120305: E tensorflow/compiler/xla/service/gpu/cudnn_conv_algorithm_picker.cc:536] Resource exhausted: Out of memory while trying to allocate 633339904 bytes.
2020-07-10 08:25:18.229361: I tensorflow/stream_executor/cuda/cuda_driver.cc:831] failed to allocate 4.91G (5267753984 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-07-10 08:25:18.229949: I tensorflow/stream_executor/cuda/cuda_driver.cc:831] failed to allocate 4.91G (5267753984 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-07-10 08:25:18.258339: I tensorflow/stream_executor/cuda/cuda_driver.cc:831] failed to allocate 4.91G (5267753984 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-07-10 08:25:18.259126: I tensorflow/stream_executor/cuda/cuda_driver.cc:831] failed to allocate 4.91G (5267753984 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-07-10 08:25:18.333364: I tensorflow/stream_executor/cuda/cuda_driver.cc:831] failed to allocate 4.91G (5267753984 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-07-10 08:25:18.333395: E tensorflow/compiler/xla/service/gpu/cudnn_conv_algorithm_picker.cc:536] Resource exhausted: Out of memory while trying to allocate 633339904 bytes.
2020-07-10 08:25:18.398196: I tensorflow/stream_executor/cuda/cuda_driver.cc:831] failed to allocate 4.91G (5267753984 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-07-10 08:25:18.398223: E tensorflow/compiler/xla/service/gpu/cudnn_conv_algorithm_picker.cc:536] Resource exhausted: Out of memory while trying to allocate 633339904 bytes.
2020-07-10 08:25:18.514493: I tensorflow/stream_executor/cuda/cuda_driver.cc:831] failed to allocate 4.91G (5267753984 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-07-10 08:25:18.515082: I tensorflow/stream_executor/cuda/cuda_driver.cc:831] failed to allocate 4.91G (5267753984 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-07-10 08:25:18.515755: I tensorflow/stream_executor/cuda/cuda_driver.cc:831] failed to allocate 4.91G (5267753984 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-07-10 08:25:18.516328: I tensorflow/stream_executor/cuda/cuda_driver.cc:831] failed to allocate 4.91G (5267753984 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-07-10 08:25:18.592103: I tensorflow/stream_executor/cuda/cuda_driver.cc:831] failed to allocate 4.91G (5267753984 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-07-10 08:25:18.592686: I tensorflow/stream_executor/cuda/cuda_driver.cc:831] failed to allocate 4.91G (5267753984 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-07-10 08:25:18.797908: I tensorflow/stream_executor/cuda/cuda_driver.cc:831] failed to allocate 4.91G (5267753984 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-07-10 08:25:18.798496: I tensorflow/stream_executor/cuda/cuda_driver.cc:831] failed to allocate 4.91G (5267753984 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-07-10 08:25:18.799100: I tensorflow/stream_executor/cuda/cuda_driver.cc:831] failed to allocate 4.91G (5267753984 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-07-10 08:25:18.800073: I tensorflow/stream_executor/cuda/cuda_driver.cc:831] failed to allocate 4.91G (5267753984 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-07-10 08:25:18.907403: I tensorflow/stream_executor/cuda/cuda_driver.cc:831] failed to allocate 4.91G (5267753984 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-07-10 08:25:18.908114: I tensorflow/stream_executor/cuda/cuda_driver.cc:831] failed to allocate 4.91G (5267753984 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-07-10 08:25:19.045201: I tensorflow/stream_executor/cuda/cuda_driver.cc:831] failed to allocate 4.91G (5267753984 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-07-10 08:25:19.045828: I tensorflow/stream_executor/cuda/cuda_driver.cc:831] failed to allocate 4.91G (5267753984 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-07-10 08:25:19.281612: I tensorflow/stream_executor/cuda/cuda_driver.cc:831] failed to allocate 4.91G (5267753984 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-07-10 08:25:19.282282: I tensorflow/stream_executor/cuda/cuda_driver.cc:831] failed to allocate 4.91G (5267753984 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-07-10 08:25:19.282906: I tensorflow/stream_executor/cuda/cuda_driver.cc:831] failed to allocate 4.91G (5267753984 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-07-10 08:25:19.283512: I tensorflow/stream_executor/cuda/cuda_driver.cc:831] failed to allocate 4.91G (5267753984 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-07-10 08:25:19.524994: I tensorflow/stream_executor/cuda/cuda_driver.cc:831] failed to allocate 4.91G (5267753984 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-07-10 08:25:19.525013: W tensorflow/core/common_runtime/bfc_allocator.cc:305] Garbage collection: deallocate free memory regions (i.e., allocations) so that we can re-allocate a larger region to avoid OOM due to memory fragmentation. If you see this message frequently, you are running near the threshold of the available device memory and re-allocation may incur great performance overhead. You may try smaller batch sizes to observe the performance impact. Set TF_ENABLE_GPU_GARBAGE_COLLECTION=false if you'd like to disable this feature.
2020-07-10 08:25:19.565086: I tensorflow/stream_executor/cuda/cuda_driver.cc:831] failed to allocate 5.91G (6341495808 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-07-10 08:25:19.565962: I tensorflow/stream_executor/cuda/cuda_driver.cc:831] failed to allocate 5.91G (6341495808 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-07-10 08:25:19.566605: I tensorflow/stream_executor/cuda/cuda_driver.cc:831] failed to allocate 5.91G (6341495808 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-07-10 08:25:19.567237: I tensorflow/stream_executor/cuda/cuda_driver.cc:831] failed to allocate 5.91G (6341495808 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-07-10 08:25:19.567866: I tensorflow/stream_executor/cuda/cuda_driver.cc:831] failed to allocate 5.91G (6341495808 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-07-10 08:25:19.568489: I tensorflow/stream_executor/cuda/cuda_driver.cc:831] failed to allocate 5.91G (6341495808 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-07-10 08:25:19.569111: I tensorflow/stream_executor/cuda/cuda_driver.cc:831] failed to allocate 5.91G (6341495808 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-07-10 08:25:19.569731: I tensorflow/stream_executor/cuda/cuda_driver.cc:831] failed to allocate 5.91G (6341495808 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-07-10 08:25:19.645724: I tensorflow/stream_executor/cuda/cuda_driver.cc:831] failed to allocate 5.91G (6341495808 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-07-10 08:25:19.646335: I tensorflow/stream_executor/cuda/cuda_driver.cc:831] failed to allocate 5.91G (6341495808 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-07-10 08:25:19.646929: I tensorflow/stream_executor/cuda/cuda_driver.cc:831] failed to allocate 5.91G (6341495808 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-07-10 08:25:19.647622: I tensorflow/stream_executor/cuda/cuda_driver.cc:831] failed to allocate 5.91G (6341495808 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-07-10 08:25:19.648273: I tensorflow/stream_executor/cuda/cuda_driver.cc:831] failed to allocate 5.91G (6341495808 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-07-10 08:25:19.648881: I tensorflow/stream_executor/cuda/cuda_driver.cc:831] failed to allocate 5.91G (6341495808 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-07-10 08:25:19.649458: I tensorflow/stream_executor/cuda/cuda_driver.cc:831] failed to allocate 5.91G (6341495808 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-07-10 08:25:19.650032: I tensorflow/stream_executor/cuda/cuda_driver.cc:831] failed to allocate 5.91G (6341495808 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-07-10 08:25:19.650680: I tensorflow/stream_executor/cuda/cuda_driver.cc:831] failed to allocate 5.91G (6341495808 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-07-10 08:25:19.651256: I tensorflow/stream_executor/cuda/cuda_driver.cc:831] failed to allocate 5.91G (6341495808 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-07-10 08:25:19.651890: I tensorflow/stream_executor/cuda/cuda_driver.cc:831] failed to allocate 5.91G (6341495808 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-07-10 08:25:19.652470: I tensorflow/stream_executor/cuda/cuda_driver.cc:831] failed to allocate 5.91G (6341495808 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-07-10 08:25:19.725841: I tensorflow/stream_executor/cuda/cuda_driver.cc:831] failed to allocate 5.91G (6341495808 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-07-10 08:25:19.726432: I tensorflow/stream_executor/cuda/cuda_driver.cc:831] failed to allocate 5.91G (6341495808 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-07-10 08:25:19.744827: I tensorflow/stream_executor/cuda/cuda_driver.cc:831] failed to allocate 5.91G (6341495808 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-07-10 08:25:19.745421: I tensorflow/stream_executor/cuda/cuda_driver.cc:831] failed to allocate 5.91G (6341495808 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-07-10 08:25:19.757516: I tensorflow/stream_executor/cuda/cuda_driver.cc:831] failed to allocate 5.91G (6341495808 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-07-10 08:25:19.757812: I tensorflow/compiler/jit/xla_compilation_cache.cc:238] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.
2020-07-10 08:25:19.758870: W tensorflow/core/framework/op_kernel.cc:1651] OP_REQUIRES failed at xla_ops.cc:502 : Resource exhausted: Out of memory while trying to allocate 427819008 bytes.
INFO:tensorflow:Error reported to Coordinator: <class 'tensorflow.python.framework.errors_impl.ResourceExhaustedError'>, 2 root error(s) found.
(0) Resource exhausted: Out of memory while trying to allocate 427819008 bytes.
[[{{node cluster_0_1/xla_compile}}]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

[[cluster_1_1/merge_oidx_0/_71]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

(1) Resource exhausted: Out of memory while trying to allocate 427819008 bytes.
[[{{node cluster_0_1/xla_compile}}]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

0 successful operations.
0 derived errors ignored.
I0710 08:25:19.759793 140529772136256 coordinator.py:224] Error reported to Coordinator: <class 'tensorflow.python.framework.errors_impl.ResourceExhaustedError'>, 2 root error(s) found.
(0) Resource exhausted: Out of memory while trying to allocate 427819008 bytes.
[[{{node cluster_0_1/xla_compile}}]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

[[cluster_1_1/merge_oidx_0/_71]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

(1) Resource exhausted: Out of memory while trying to allocate 427819008 bytes.
[[{{node cluster_0_1/xla_compile}}]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

0 successful operations.
0 derived errors ignored.
Traceback (most recent call last):
File "/usr/lib/python3/dist-packages/tensorflow_core/python/client/session.py", line 1365, in _do_call
return fn(*args)
File "/usr/lib/python3/dist-packages/tensorflow_core/python/client/session.py", line 1350, in _run_fn
target_list, run_metadata)
File "/usr/lib/python3/dist-packages/tensorflow_core/python/client/session.py", line 1443, in _call_tf_sessionrun
run_metadata)
tensorflow.python.framework.errors_impl.ResourceExhaustedError: 2 root error(s) found.
(0) Resource exhausted: Out of memory while trying to allocate 427819008 bytes.
[[{{node cluster_0_1/xla_compile}}]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

[[cluster_1_1/merge_oidx_0/_71]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

(1) Resource exhausted: Out of memory while trying to allocate 427819008 bytes.
[[{{node cluster_0_1/xla_compile}}]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

0 successful operations.
0 derived errors ignored.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "tf_cnn_benchmarks.py", line 73, in <module>
app.run(main)  # Raises error on invalid flags, unlike tf.app.run()
File "/usr/lib/python3/dist-packages/absl/app.py", line 299, in run
_run_main(main, args)
File "/usr/lib/python3/dist-packages/absl/app.py", line 250, in _run_main
sys.exit(main(argv))
File "tf_cnn_benchmarks.py", line 68, in main
bench.run()
File "/home/ubuntu/lambda-tensorflow-benchmark/benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py", line 1884, in run
return self._benchmark_train()
File "/home/ubuntu/lambda-tensorflow-benchmark/benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py", line 2089, in _benchmark_train
return self._benchmark_graph(result_to_benchmark, eval_build_results)
File "/home/ubuntu/lambda-tensorflow-benchmark/benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py", line 2296, in _benchmark_graph
is_chief, summary_writer, profiler)
File "/home/ubuntu/lambda-tensorflow-benchmark/benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py", line 2434, in benchmark_with_session
is_chief))
File "/home/ubuntu/lambda-tensorflow-benchmark/benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py", line 871, in benchmark_one_step
results = sess.run(fetches, options=run_options, run_metadata=run_metadata)
File "/usr/lib/python3/dist-packages/tensorflow_core/python/client/session.py", line 956, in run
run_metadata_ptr)
File "/usr/lib/python3/dist-packages/tensorflow_core/python/client/session.py", line 1180, in _run
feed_dict_tensor, options, run_metadata)
File "/usr/lib/python3/dist-packages/tensorflow_core/python/client/session.py", line 1359, in _do_run
run_metadata)
File "/usr/lib/python3/dist-packages/tensorflow_core/python/client/session.py", line 1384, in _do_call
raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.ResourceExhaustedError: 2 root error(s) found.
(0) Resource exhausted: Out of memory while trying to allocate 427819008 bytes.
[[{{node cluster_0_1/xla_compile}}]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

[[cluster_1_1/merge_oidx_0/_71]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

(1) Resource exhausted: Out of memory while trying to allocate 427819008 bytes.
[[{{node cluster_0_1/xla_compile}}]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

0 successful operations.
0 derived errors ignored.
